export const environment = {
    production: true,
    HOST: 'http://tutoring.io',
    WEBCAL: 'webcal://api.tutoring.io',
    API_HOST: 'https://api.tutoring.io',
    REFERRAL_URL: "https://tutoring.io",
    API_SOCKET_URL: 'wss://api.tutoring.io/ws',
    COOKIE_DOMAIN: '.tutoring.io',
    MAPBOX_TOKEN: '',
    FacebookAppID: '',
    GoogleMapsApiKey: '',
    INTERCOM_APP_ID: '',
    NATIVEFORMS_LICENSE: '',
    SURVEY_DAYS_RECURRENT: 7,
    GOOGLE_API_KEY: "",
    GoogleAppID: "",
    LinkedInAppID: "",
    TwitterAppID: "",
};
